version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1457353897
layout:
  top: {  }
  navigation: {  }
  header: {  }
  /slideshow/:
    -
      - simplecontent-7561
  /above/:
    -
      - custom-2875
    -
      - custom-4860
    -
      - 'custom-9868 50'
      - 'custom-4807 50'
    -
      - 'custom-3780 33.3'
      - 'custom-7528 33.3'
      - 'custom-3751 33.3'
    -
      - 'custom-6453 25'
      - 'custom-6496 25'
      - 'custom-3872 25'
      - 'custom-9371 25'
    -
      - custom-9988
    -
      - 'custom-4289 25'
      - 'custom-1256 50'
      - 'custom-2720 25'
    -
      - 'custom-5527 26'
      - 'custom-1752 31'
      - 'custom-4132 43'
    -
      - custom-5410
  showcase: {  }
  utility: {  }
  feature: {  }
  /container-main/:
    -
      -
        'sidebar 30':
          -
            - 'custom-6468 50'
            - 'custom-4397 50'
          -
            - custom-8735
          -
            - 'custom-5316 50'
            - 'custom-9449 50'
      -
        'mainbar 40':
          -
            - custom-6027
          -
            - 'custom-2369 50'
            - 'custom-2507 50'
      -
        'aside 30':
          -
            - custom-2846
  expanded: {  }
  extension: {  }
  bottom: {  }
  footer: {  }
  copyright: {  }
  offcanvas: {  }
structure:
  top:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  slideshow:
    type: section
    attributes:
      boxed: '3'
      class: ''
  above:
    type: section
    attributes:
      boxed: '3'
      class: ''
  showcase:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  utility:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  feature:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  sidebar:
    type: section
    block:
      class: equal-height
  mainbar:
    type: section
    block:
      class: equal-height
  aside:
    block:
      class: equal-height
  container-main:
    attributes:
      boxed: '3'
      class: ''
      extra: {  }
  expanded:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  extension:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  bottom:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  copyright:
    type: section
    inherit:
      outline: default
      include:
        - children
        - attributes
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  simplecontent-7561:
    title: 'Rows & Columns Example'
    attributes:
      class: ''
      title: ''
      items:
        -
          layout: header
          created_date: ''
          content_title: 'Rows & Columns Example'
          author: ''
          leading_content: ''
          main_content: ''
          readmore_label: ''
          readmore_link: ''
          readmore_class: ''
          readmore_target: _self
          title: 'Rows & Columns Example'
  custom-2875:
    title: 'Equal Width Examples'
    attributes:
      html: "<h1 class=\"g-title\">Equal Width Examples</h1>\n<p>The examples below demonstrate up to four blocks in a row, of equal widths. Each block has the Box 1, 3, 4 or 5 block variation applied to show separation between the blocks.</p>"
    block:
      variations: 'title2 box5'
  custom-4860:
    title: 'Single Block per Row'
    attributes:
      html: '<h5>Single Block per Row</h5>'
    block:
      variations: box3
  custom-9868:
    title: 'Two Blocks per Row'
    attributes:
      html: '<h5>Two Blocks per Row</h5>'
    block:
      variations: box4
  custom-4807:
    title: 'Two Blocks per Row'
    attributes:
      html: '<h5>Two Blocks per Row</h5>'
    block:
      variations: box4
  custom-3780:
    title: 'Three Blocks per Row'
    attributes:
      html: '<h5>Three Blocks per Row</h5>'
    block:
      variations: box3
  custom-7528:
    title: 'Three Blocks per Row'
    attributes:
      html: '<h5>Three Blocks per Row</h5>'
    block:
      variations: box3
  custom-3751:
    title: 'Three Blocks per Row'
    attributes:
      html: '<h5>Three Blocks per Row</h5>'
    block:
      variations: box3
  custom-6453:
    title: 'Four Blocks per Row'
    attributes:
      html: '<h5>Four Blocks per Row</h5>'
    block:
      variations: box4
  custom-6496:
    title: 'Four Blocks per Row'
    attributes:
      html: '<h5>Four Blocks per Row</h5>'
    block:
      variations: box4
  custom-3872:
    title: 'Four Blocks per Row'
    attributes:
      html: '<h5>Four Blocks per Row</h5>'
    block:
      variations: box4
  custom-9371:
    title: 'Four Blocks per Row'
    attributes:
      html: '<h5>Four Blocks per Row</h5>'
    block:
      variations: box4
  custom-9988:
    title: 'Different Width Examples'
    attributes:
      html: "<h1 class=\"g-title\">Different Width Examples</h1>\n<p>The examples below demonstrate up to four blocks in a row, of differing widths. Each block has the Box 1, 3 or 4 block variation applied to show separation between the blocks.</p>"
    block:
      class: 'nomarginbottom nopaddingbottom'
      variations: title2
  custom-4289:
    title: '25% Width Block'
    attributes:
      html: '<h5>25% Width Block</h5>'
    block:
      variations: box4
  custom-1256:
    title: '75% Width Block'
    attributes:
      html: '<h5>75% Width Block</h5>'
    block:
      variations: box4
  custom-2720:
    title: '25% Width Block'
    attributes:
      html: '<h5>25% Width Block</h5>'
    block:
      variations: box4
  custom-5527:
    title: '26% Width Block'
    attributes:
      html: '<h5>26% Width Block</h5>'
    block:
      variations: box3
  custom-1752:
    title: '31% Width Block'
    attributes:
      html: '<h5>31% Width Block</h5>'
    block:
      variations: box3
  custom-4132:
    title: '43% Width Block'
    attributes:
      html: '<h5>43% Width Block</h5>'
    block:
      variations: box3
  custom-5410:
    title: 'Mainbody Examples'
    attributes:
      html: "<h1 class=\"g-title\">Mainbody Examples</h1>\n<p>The mainbody is a unique section in Gantry 5 that allows for up to three columns (varies on outline) to be configured independently from one another. Therefore, you can have multiple rows and columns in each column, creating very unique layout possibilities. In the example below, block variations are used to delineate each block.</p>"
    block:
      class: 'nomarginbottom nopaddingbottom'
      variations: title2
  custom-6468:
    title: 'Custom HTML'
    attributes:
      html: 'Lorem ipsum dolor sit amet adiping elit.'
    block:
      variations: box3
  custom-4397:
    title: 'Custom HTML'
    attributes:
      html: 'Donec sit amet nibh. Vivamus non arcu.'
    block:
      variations: box4
  custom-8735:
    title: 'Custom HTML'
    attributes:
      html: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet nibh.'
    block:
      variations: box6
  custom-5316:
    title: 'Custom HTML'
    attributes:
      html: 'Integer fermen tum elit in sem magnus tellus.'
    block:
      variations: box4
  custom-9449:
    title: 'Custom HTML'
    attributes:
      html: 'Sed ac arcu. Sed tincidunt libero eu dolor.'
      filter: '0'
    block:
      variations: box2
  custom-6027:
    title: 'Custom HTML'
    attributes:
      html: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque id tortor. In vitae sapien. Nunc quis tellus.'
    block:
      variations: box4
  custom-2369:
    title: 'Custom HTML'
    attributes:
      html: "\n                            Praesent sed nisl tempor est pulvinar tristique. Maecenas non lorem quis mi laoreet adipiscing. Sed ac arcu. Sed tincidunt libero eu dolor. Cras pharetra posuere eros. Donec ac eros tincidunt.\n            \n    "
    block:
      variations: box4
      fixed: '1'
  custom-2507:
    title: 'Custom HTML'
    attributes:
      html: 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean et libero. Nam aliquam. Quisque vitae tortor id neque dignissim laoreet. Duis eu ante.'
    block:
      variations: box4
  custom-2846:
    title: 'Custom HTML'
    attributes:
      html: 'Nullam eget neque. Nullam imperdiet venenatis ligula. Integer a leo. Nunc consectetur. Maecenas sem. Proin vulputate, massa vel volutpat laoreet, purus erat pretium ligula, eget varius arcu nibh sed libero. Fusce ante. Nullam interdum aliquet metus. Ut ultrices vestibulum tellus. Praesent quis erat. Nam id turpis sit amet neque cursus luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque id tortor. In vitae sapien. Nunc quis tellus. '
    block:
      variations: box2
